USE [master]
GO

/****** Object:  Database [Stock_Market]    Script Date: 5/27/2023 3:07:18 AM ******/
CREATE DATABASE [Stock_Market]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Stock_Market', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQL2019\MSSQL\DATA\Stock_Market.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Stock_Market_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQL2019\MSSQL\DATA\Stock_Market_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Stock_Market].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Stock_Market] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Stock_Market] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Stock_Market] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Stock_Market] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Stock_Market] SET ARITHABORT OFF 
GO

ALTER DATABASE [Stock_Market] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Stock_Market] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Stock_Market] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Stock_Market] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Stock_Market] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Stock_Market] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Stock_Market] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Stock_Market] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Stock_Market] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Stock_Market] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Stock_Market] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Stock_Market] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Stock_Market] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Stock_Market] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Stock_Market] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Stock_Market] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Stock_Market] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Stock_Market] SET RECOVERY FULL 
GO

ALTER DATABASE [Stock_Market] SET  MULTI_USER 
GO

ALTER DATABASE [Stock_Market] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Stock_Market] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Stock_Market] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Stock_Market] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Stock_Market] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Stock_Market] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Stock_Market] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Stock_Market] SET  READ_WRITE 
GO


